# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
NODE_COUNT = 2

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    #config.vm.synced_folder "/Users/dstibrany/code/golang/src/", "/home/vagrant/code/golang/src"
    config.vbguest.auto_update = false
    config.vm.box = "ubuntu/trusty64"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = "1"
    end

    NODE_COUNT.times do |i|
        id = i + 1
        node_id = "node#{id}"
        config.vm.define node_id do |node|
            node.vm.network :forwarded_port, guest: 22, host: "222#{id}", id: "ssh"
            node.vm.network "private_network", ip: "192.168.50.1#{id}"
            node.vm.hostname = node_id
        end
    end
end