" defaults
" --------
inoremap jj <ESC>
let mapleader=","
filetype plugin indent on
syntax on
set encoding=utf-8
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set number
set showmatch  " highlight matching [{()}]
set wildmenu   " visual autocomplete for command menu
set cursorline " highlight current line

" Use CTRL-S for saving, also in Insert mode
noremap <C-S> :update<CR>
vnoremap <C-S> <C-C>:update<CR>
inoremap <C-S> <C-O>:update<CR>

" pathogen
" --------
execute pathogen#infect()

" solarized
" ---------
set background=dark
colorscheme solarized
call togglebg#map("<F5>")

" airline
" -------
let g:airline_powerline_fonts = 1
let g:airline_theme = 'base16'

" easy motion
" -----------
let g:EasyMotion_do_mapping = 0 " Disable default mappings

" Bi-directional find motion
" Jump to anywhere you want with minimal keystrokes, with just one key
" binding.
" `s{char}{label}`
nmap s <Plug>(easymotion-s)
" or
" `s{char}{char}{label}`
" Need one more keystroke, but on average, it may be more comfortable.
nmap s <Plug>(easymotion-s2)

" Turn on case sensitive feature
let g:EasyMotion_smartcase = 1

" JK motions: Line motions
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)

" Yank text to the OS X clipboard
" -------------------------------
noremap <leader>y "*y
noremap <leader>yy "*Y

" Preserve indentation while pasting text from the OS X clipboard
noremap <leader>p :set paste<CR>:put  *<CR>:set nopaste<CR>
nnoremap <F6> :set invpaste paste?<CR>
set pastetoggle=<F6>
set showmode
