syntax enable
set incsearch
set nu
set autoindent
set smartindent
set tabstop=2
set expandtab
set shiftwidth=2
set cursorline
set smarttab
set smartcase
set ignorecase
set shortmess+=IA "No swap-file message 
set fillchars=vert:│
set nocompatible
set laststatus=2
set encoding=utf-8
set bg=dark

set tabstop=4
set shiftwidth=4
set expandtab
""""""""""""""""""""""""""""
command! Q q
command! Qall qall
command! W w
command! Wall wall
command! WQ wq
command! Wq wq
nmap Q: :q
"""""""""""""""""""""""""""""
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
filetype off
Bundle 'gmarik/vundle'

Bundle 'Lokaltog/vim-powerline'
Bundle 'kien/ctrlp.vim'

filetype plugin indent on
""""""""""""""""""""""""""""
set t_Co=256
"let g:solarized_termcolors=256
set background=dark
colorscheme molokai
"""""""""""""""""""""""""""""
au BufNewFile,BufRead *.rkt set filetype=racket
au BufNewFile,BufRead *.c set cindent
au BufNewFile,BufRead *.coffee set filetype=coffee

"""""""""""""""""""""""""""""
inoremap jj <Esc>
map - <C-W>w
map <Tab> gt
autocmd BufRead *.txt set tw=80
